package com.infobip.openapi.mcp.openapi.tool;

import com.infobip.openapi.mcp.McpRequestContext;
import io.modelcontextprotocol.spec.McpSchema;
import org.jspecify.annotations.NullMarked;

/**
 * ToolCallFilter interface allows interception and modification of MCP tool calls before and after execution.
 * <p>
 * Filters are invoked in a chain-of-responsibility pattern, with each filter having the option to:
 * <ul>
 *   <li>Inspect or modify the incoming request before delegating to the next filter</li>
 *   <li>Delegate to the next filter in the chain via {@link ToolCallFilterChain#doFilter(McpRequestContext, McpSchema.CallToolRequest)}</li>
 *   <li>Inspect or modify the response returned from the chain</li>
 *   <li>Short-circuit the chain by returning a response without delegating</li>
 * </ul>
 * <p>
 * Filters are invoked in the order defined by Spring's {@link org.springframework.core.Ordered} interface.
 * The default {@link RegisteredTool} filter, which has the lowest precedence ({@link org.springframework.core.Ordered#LOWEST_PRECEDENCE}),
 * is responsible for executing the actual HTTP API call to the backend service. Filters with higher precedence
 * (lower order values) can intercept tool calls before the HTTP request is made.
 *
 * @see ToolCallFilterChain
 * @see RegisteredTool
 */
@NullMarked
public interface ToolCallFilter {

    /**
     * Filters the provided tool call request.
     * <p>
     * Implementations should typically delegate to the next filter in the chain by calling
     * {@link ToolCallFilterChain#doFilter(McpRequestContext, McpSchema.CallToolRequest)}.
     * Filters may choose to short-circuit the chain by returning a response directly without delegation.
     *
     * @param ctx   the MCP request context containing transport metadata and HTTP request information
     * @param req   the tool call request to filter
     * @param chain the filter chain to delegate to the next filter
     * @return the tool call result, either from the chain or generated by this filter
     */
    McpSchema.CallToolResult doFilter(McpRequestContext ctx, McpSchema.CallToolRequest req, ToolCallFilterChain chain);
}
