package com.infobip.openapi.mcp.resource;

import com.infobip.openapi.mcp.McpRequestContext;
import io.modelcontextprotocol.spec.McpSchema;
import org.jspecify.annotations.NullMarked;

/**
 * ResourceCallFilter interface allows interception and modification of MCP resource reads before and after execution.
 * <p>
 * Filters are invoked in a chain-of-responsibility pattern, with each filter having the option to:
 * <ul>
 *   <li>Inspect or modify the incoming request before delegating to the next filter</li>
 *   <li>Delegate to the next filter in the chain via {@link ResourceCallFilterChain#doFilter(McpRequestContext, McpSchema.ReadResourceRequest)}</li>
 *   <li>Inspect or modify the response returned from the chain</li>
 *   <li>Short-circuit the chain by returning a response without delegating</li>
 * </ul>
 * <p>
 * Filters are invoked in the order defined by Spring's {@link org.springframework.core.Ordered} interface.
 * The default {@link RegisteredResource} filter, which has the lowest precedence ({@link org.springframework.core.Ordered#LOWEST_PRECEDENCE}),
 * is responsible for executing the actual resource resolution (inline content or backend HTTP call).
 * Filters with higher precedence (lower order values) can intercept resource reads before resolution happens.
 *
 * @see ResourceCallFilterChain
 * @see RegisteredResource
 */
@NullMarked
public interface ResourceCallFilter {

    /**
     * Filters the provided resource read request.
     * <p>
     * Implementations should typically delegate to the next filter in the chain by calling
     * {@link ResourceCallFilterChain#doFilter(McpRequestContext, McpSchema.ReadResourceRequest)}.
     * Filters may choose to short-circuit the chain by returning a response directly without delegation.
     *
     * @param ctx   the MCP request context containing transport metadata and HTTP request information
     * @param req   the resource read request to filter
     * @param chain the filter chain to delegate to the next filter
     * @return the resource read result, either from the chain or generated by this filter
     */
    McpSchema.ReadResourceResult doFilter(
            McpRequestContext ctx, McpSchema.ReadResourceRequest req, ResourceCallFilterChain chain);
}
