package com.infobip.openapi.mcp.prompt;

import com.infobip.openapi.mcp.McpRequestContext;
import io.modelcontextprotocol.spec.McpSchema;
import org.jspecify.annotations.NullMarked;

/**
 * PromptCallFilter interface allows interception and modification of MCP prompt calls before and after execution.
 * <p>
 * Filters are invoked in a chain-of-responsibility pattern, with each filter having the option to:
 * <ul>
 *   <li>Inspect or modify the incoming request before delegating to the next filter</li>
 *   <li>Delegate to the next filter in the chain via {@link PromptCallFilterChain#doFilter(McpRequestContext, McpSchema.GetPromptRequest)}</li>
 *   <li>Inspect or modify the response returned from the chain</li>
 *   <li>Short-circuit the chain by returning a response without delegating</li>
 * </ul>
 * <p>
 * Filters are invoked in the order defined by Spring's {@link org.springframework.core.Ordered} interface.
 * The default {@link RegisteredPrompt} filter, which has the lowest precedence ({@link org.springframework.core.Ordered#LOWEST_PRECEDENCE}),
 * is responsible for executing the actual prompt resolution (inline template rendering or backend HTTP call).
 * Filters with higher precedence (lower order values) can intercept prompt calls before resolution happens.
 *
 * @see PromptCallFilterChain
 * @see RegisteredPrompt
 */
@NullMarked
public interface PromptCallFilter {

    /**
     * Filters the provided prompt call request.
     * <p>
     * Implementations should typically delegate to the next filter in the chain by calling
     * {@link PromptCallFilterChain#doFilter(McpRequestContext, McpSchema.GetPromptRequest)}.
     * Filters may choose to short-circuit the chain by returning a response directly without delegation.
     *
     * @param ctx   the MCP request context containing transport metadata and HTTP request information
     * @param req   the prompt call request to filter
     * @param chain the filter chain to delegate to the next filter
     * @return the prompt result, either from the chain or generated by this filter
     */
    McpSchema.GetPromptResult doFilter(
            McpRequestContext ctx, McpSchema.GetPromptRequest req, PromptCallFilterChain chain);
}
